AWSTemplateFormatVersion: "2010-09-09"
Description: >
  Creates dynamo db necessary for creating file conversion request metadata

Parameters:
  DynamoDBConversionTableName:
    Type: String
    Default: 'FileConversionRequests'

Resources:
  SessionTable:
    Type: 'AWS::DynamoDB::Table'
    Properties:
      AttributeDefinitions:
        - AttributeName: 'id'
          AttributeType: 'S'
        - AttributeName: 'sessionId'
          AttributeType: 'S'
      GlobalSecondaryIndexes:
        - IndexName: 'Session'
          KeySchema:
            - AttributeName: 'sessionId'
              KeyType: 'HASH'
          Projection:
            NonKeyAttributes:
              - 'id'
              - 'fileName'
              - 'conversionStatus'
            ProjectionType: 'INCLUDE'
          ProvisionedThroughput:
            ReadCapacityUnits: 5
            WriteCapacityUnits: 5
      KeySchema:
        - AttributeName: 'id'
          KeyType: 'HASH'
      ProvisionedThroughput:
        ReadCapacityUnits: 5
        WriteCapacityUnits: 5
      TableName: !Ref DynamoDBConversionTableName
      TimeToLiveSpecification:
        AttributeName: 'expirationTime'
        Enabled: True