AWSTemplateFormatVersion: "2010-09-09"
Description: >
  Creates dynamo db necessary for creating file conversion sessions

Parameters:
  DynamoDBSessionTableName:
    Type: String
    Default: 'FileConversionSessions'

Resources:
  SessionTable:
    Type: 'AWS::DynamoDB::Table'
    Properties:
      AttributeDefinitions:
        - AttributeName: 'id'
          AttributeType: 'S'
        - AttributeName: 'emailAddress'
          AttributeType: 'S'
      GlobalSecondaryIndexes:
        - IndexName: 'Email'
          KeySchema:
            - AttributeName: 'emailAddress'
              KeyType: 'HASH'
          Projection:
            NonKeyAttributes:
              - 'id'
            ProjectionType: 'INCLUDE'
          ProvisionedThroughput:
            ReadCapacityUnits: 5
            WriteCapacityUnits: 5
      KeySchema:
        - AttributeName: 'id'
          KeyType: 'HASH'
      ProvisionedThroughput:
        ReadCapacityUnits: 5
        WriteCapacityUnits: 5
      TableName: !Ref DynamoDBSessionTableName
      TimeToLiveSpecification:
        AttributeName: 'expirationTime'
        Enabled: True